@mtgv2_api_HostAddress = http://localhost:5043

# Test OData endpoint (will fail if no data, but tests the setup)
GET {{mtgv2_api_HostAddress}}/odata/cards
Accept: application/json

###

GET {{mtgv2_api_HostAddress}}/odata/card_combos
Accept: application/json
